Repository edgexfoundry/go-mod-bootstrap, pull requests merged in 2020-02, with the labels that each got.

#42 Add RunAndReturnWaitGroup() to bootstrap.go
  bootstrap/bootstrap.go
  go.mod
Labels: 3-high, enhancement, geneva

#45 Added NewDefaultCommonFlagsWithoutUsage. Simplified
  bootstrap/bootstrap.go
  bootstrap/commandline/common_test.go
  bootstrap/config/config.go
  bootstrap/config/environment.go
  bootstrap/config/environment_test.go
  bootstrap/config/file.go
  bootstrap/config/provider.go
  bootstrap/container/logging.go
  bootstrap/container/registry.go
  bootstrap/container/secret.go
  bootstrap/flags/flags.go
  bootstrap/flags/flags_test.go
  bootstrap/handlers/secret/secret.go
Labels: 1-low, enhancement, geneva

#47 Add ability to notify bootstrap consumer of config update
  bootstrap/bootstrap.go
  bootstrap/config/config.go
Labels: 1-low, enhancement, geneva

#43 Update the secret's BootstrapHandler to use the latest NewSecretClient
  bootstrap/handlers/secret/client/mockserver_test.go
  bootstrap/handlers/secret/client/testdata/replacement.json
  bootstrap/handlers/secret/client/testdata/testToken.json
  bootstrap/handlers/secret/client/vaultclient.go
  bootstrap/handlers/secret/client/vaultclient_test.go
  bootstrap/handlers/secret/secret.go
  go.mod
Labels: enhancement, geneva, security-services

#51 Services using registry are immediately unregistered with the registry
  bootstrap/bootstrap.go
Labels: 3-high, bug, geneva
