Repository edgexfoundry/go-mod-bootstrap, pull requests merged in 2023-02, with the labels that each got.

#434 refactor!: Replace topics from config with new constants
  bootstrap/handlers/clients.go
  bootstrap/handlers/clients_test.go
  bootstrap/handlers/messaging.go
  bootstrap/handlers/messaging_test.go
  bootstrap/handlers/metrics.go
  bootstrap/handlers/metrics_test.go
  bootstrap/metrics/reporter.go
  bootstrap/metrics/reporter_test.go
  config/types.go
  go.mod
  go.sum
Labels: enhancement, breaking-change

#446 feat: implement IsRegistered to metrics manager
  bootstrap/interfaces/metrics.go
  bootstrap/metrics/manager.go
Labels: enhancement

#453 fix: Consume MessageBus Request fix
  go.mod
  go.sum
Labels: bug
